version: '3.8'

volumes:
  mysql-volume:
  vendor-store:
  node_modules-store:

services:
  app:
    container_name: housework-app
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    volumes:
      - ./src/:/var/www/html
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=${DB_NAME}
      - DB_USERNAME=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}

  web:
    container_name: housework-web
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    ports:
      - ${WEB_PORT}:443
    depends_on:
      - app
    volumes:
      - ./src/:/var/www/html
      - ./docker/nginx/conf/certs/:/etc/nginx/certs
      - vendor-store:/var/www/html/vendor
      - node_modules-store:/var/www/html/node_modules

  db:
    container_name: housework-db
    build:
      context: .
      dockerfile: ./docker/mysql/Dockerfile
    ports:
      - ${DB_PORT}:3306
    user: 1000:1000
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      TZ: 'Asia/Tokyo'
    volumes:
      - mysql-volume:/var/lib/mysql
